In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
python.exe -m pip install --upgrade pip

SyntaxError: invalid syntax (842801469.py, line 1)

In [3]:
pip install --upgrade pip

   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----------------------- ---------------- 1.0/1.8 MB 12.7 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 12.2 MB/s  0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 25.3
    Uninstalling pip-25.3:
      Successfully uninstalled pip-25.3
Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np

# Create One D Array
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [ ]:
arr2 = np.array([1,2,3,4,5,6])
# 1 Row 6 Columns
arr2.reshape(1,6)  

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
# 2d Array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2) 
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [ ]:
#Just Like List comprehension 
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
# All element is one
np.ones((3,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#Identity Matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# Nuumpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element Wise Addition
print(f"Addition : {arr1+arr2}")

#Element wise Subs
print(f"Subs : {arr1-arr2}")

#Element wise Multiply
print(f"Multiple : {arr1*arr2}")

#Element wise Division
print(f"Power : {arr1/arr2}")


Addition : [11 22 33 44 55]
Subs : [ -9 -18 -27 -36 -45]
Multiple : [ 10  40  90 160 250]
Power : [0.1 0.1 0.1 0.1 0.1]


In [24]:
arr = np.array([2,3,4,5,6])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [32]:
# Slicing and Indexing 
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr1)
print(arr1[0][2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
3


In [ ]:
#   Every element from 2 row to n and 3 column to n
arr1[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15]])

In [36]:
print(arr1[1:,1:3])

[[ 7  8]
 [12 13]]


In [ ]:
# Modify Array Element
# Change zero row zero column element
arr1[0,0] = 10  
print(arr1)

[[10  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [45]:
## Logical Operations
data = np.array([1,2,3,4,6,7,8,9,10])
data[(data>5) & (data<8)]

array([6, 7])